---
title: Patrick Croke
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Patrick Croke
  tagline: ''
  logo_img: ''
  bg_img: "/images/6.jpg"
  has_nav: true
  has_social: true
footer:
  content: "&copy; 2020, Patrick Croke, All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
